### ISSUE TITLE
maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by mrx23dot** [iogf/ehp#1]
Hi, I got:

  File "ehp\ehp.py", line 112, in sail
    for indi in self[:]:
RuntimeError: maximum recursion depth exceeded while calling a Python object

Maybe it could check for even number of tags.

Thanks,

**Comment by iogf** [comment]
well, the sail method uses recursion on the tree of html entities. you probably have a really deep html document. you should increase recursion limit in python. show me the html document though.

**Comment by mrx23dot** [comment]
hmm it looks really flat to me: (although I'm searching for a non existing tag)

`import requests
from ehp import *
page = requests.get("http://stellar.cleanscape.net/products/cpp/cppmsgs.html")
content = page.text

html = Html()
dom = html.feed(page.text)

title = ""
for tag in dom.find('title'):
  title = tag.text()
  break

print(title)
`

**Comment by iogf** [comment]
well, the following code works for me.

import requests
import sys
from ehp import *
page = requests.get("http://stellar.cleanscape.net/products/cpp/cppmsgs.html")
content = page.text
sys.setrecursionlimit(10000)

html = Html()
dom = html.feed(page.text)

title = ""
for tag in dom.find('title'):
    title = tag.text()
    break

print(title)

It seems there is no title element in that document at all. I have the feeling you have a misunderstanding about.what do you plan to use EHP for? feel free to contact me on skype: arcamens

**Comment by iogf** [comment]
EHP doesnt use a recursion algorithm to build the AST for the html document although when iterating over the AST it may be the case of existing deep nested nodes(which isn't common at all) so you get recursion limit.

**Comment by iogf** [comment]
I guess that is due to the amount of <br> elements. I suppose it is due to the underlying tokenizer HTMLParser class that is handling <br> incorrectly although i have to check that.

**Comment by iogf** [comment]
Yeah. HTMLParser seems to be handling <br> as a normal tag <br> </br>
So, it is nesting the elements incorrectly. It should handle <br> tags like XTag(see EHP classes for that).

**Comment by mrx23dot** [comment]
Raising recursion limit did the trick.
I'm using EHP to extract content from websites.  great tool!
Thanks for the help!
